name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      EMAIL_TO: yowelikachala@gmail.com
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: not-here
      SMTP_PASSWORD: not-here-either
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.SSH_HOST }}
          key: ${{ env.SSH_KEY }}
          username: ${{ env.SSH_USERNAME }}

      - name: Send Deployment Status Email
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          subject: 'CI/CD Deployment Status'
          to: ${{ env.EMAIL_TO }}
          from: 'yowelikachala@gmail.com'
          body: 'Deployment successful!'
